#!/bin/bash
DIR="/root/.openclaw/workspace/islam-china/carousel"

# Slide 1: Cover
cat > "$DIR/s1.html" << 'EOF1'
<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{margin:0;padding:0;box-sizing:border-box}body{width:1080px;height:1080px;overflow:hidden;font-family:'Segoe UI',Tahoma,sans-serif;background:linear-gradient(135deg,#0d2137 0%,#1a3a2a 40%,#0d2137 100%);display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:80px}.ornament-top{position:absolute;top:0;left:0;right:0;height:8px;background:linear-gradient(90deg,transparent,#c8a84e,transparent)}.ornament-bottom{position:absolute;bottom:0;left:0;right:0;height:8px;background:linear-gradient(90deg,transparent,#c8a84e,transparent)}.circle{position:absolute;width:200px;height:200px;border:2px solid rgba(200,168,78,.1);border-radius:50%}.c1{top:-60px;right:-60px}.c2{bottom:-40px;left:-40px;width:150px;height:150px}.arabic{font-size:48px;color:#7fbf7f;margin-bottom:20px;position:relative;z-index:1}h1{font-size:56px;color:#c8a84e;line-height:1.2;margin-bottom:16px;position:relative;z-index:1;font-weight:800}.sub{font-size:28px;color:#a0c0a0;line-height:1.5;position:relative;z-index:1;max-width:800px}.badge{position:absolute;bottom:60px;background:rgba(200,168,78,.2);border:2px solid #c8a84e;border-radius:30px;padding:12px 32px;color:#c8a84e;font-size:22px;font-weight:600;z-index:1}</style></head><body><div class="ornament-top"></div><div class="circle c1"></div><div class="circle c2"></div><div class="arabic">بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ</div><h1>Ketika Adzan<br>Berkumandang<br>di Shanghai</h1><div class="sub">Sholat Jumat di Masjid Pudong — mengingat 1.400 tahun sejarah Islam di Negeri Tirai Bambu</div><div class="badge">🕌 Kisah Nyata dari Shanghai</div><div class="ornament-bottom"></div></body></html>
EOF1

# Slide 2: Pengalaman
cat > "$DIR/s2.html" << 'EOF2'
<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{margin:0;padding:0;box-sizing:border-box}body{width:1080px;height:1080px;overflow:hidden;font-family:'Segoe UI',Tahoma,sans-serif;background:linear-gradient(180deg,#0d2137 0%,#162d1f 100%);display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:80px}.circle{position:absolute;width:200px;height:200px;border:2px solid rgba(200,168,78,.1);border-radius:50%}.c1{top:-60px;right:-60px}.qm{font-size:120px;color:rgba(200,168,78,.3);line-height:1;margin-bottom:-30px}.quote{font-size:34px;line-height:1.6;color:#d4c080;font-style:italic;max-width:850px;margin-bottom:30px}.divider{width:80px;height:3px;background:#c8a84e;margin:24px auto}.story{font-size:26px;line-height:1.7;color:#b0c4b0;max-width:850px;text-align:left}.story strong{color:#c8a84e}</style></head><body><div class="circle c1"></div><div class="qm">"</div><div class="quote">Shaf sudah penuh. Jamaah meluber sampai ke halaman. Dan aku berpikir — bagaimana mungkin?</div><div class="divider"></div><div class="story">Di tengah kota terbesar di China — negeri yang identik dengan Konfusianisme dan Buddha — <strong>ribuan Muslim</strong> dengan tenang menjalankan sholat Jumat. Di masjid yang lebih tua dari kebanyakan masjid di Nusantara. Ada pedagang Uyghur, mahasiswa Hui, keluarga Kazakh, dan warga Shanghai yang sudah Muslim <strong>sejak lahir</strong> — keturunan komunitas yang sudah tinggal di sini ratusan tahun.</div></body></html>
EOF2

# Slide 3: Fakta
cat > "$DIR/s3.html" << 'EOF3'
<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{margin:0;padding:0;box-sizing:border-box}body{width:1080px;height:1080px;overflow:hidden;font-family:'Segoe UI',Tahoma,sans-serif;background:linear-gradient(135deg,#1a2a1a 0%,#0d1a2a 100%);display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:60px}.circle{position:absolute;width:150px;height:150px;border:2px solid rgba(200,168,78,.1);border-radius:50%;bottom:-40px;left:-40px}h2{font-size:42px;color:#c8a84e;margin-bottom:40px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;max-width:900px}.card{background:rgba(200,168,78,.08);border:1px solid rgba(200,168,78,.3);border-radius:16px;padding:28px;text-align:center}.num{font-size:48px;color:#c8a84e;font-weight:800}.label{font-size:20px;color:#a0c0a0;margin-top:8px;line-height:1.4}</style></head><body><div class="circle"></div><h2>📊 Islam di China Hari Ini</h2><div class="grid"><div class="card"><div class="num">651 M</div><div class="label">Tahun Islam<br>Resmi Masuk China</div></div><div class="card"><div class="num">~30 Juta</div><div class="label">Muslim<br>di China</div></div><div class="card"><div class="num">39.135</div><div class="label">Masjid di<br>Seluruh China</div></div><div class="card"><div class="num">10</div><div class="label">Etnis Muslim<br>Resmi Tiongkok</div></div></div></body></html>
EOF3

# Slide 4: Sejarah
cat > "$DIR/s4.html" << 'EOF4'
<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{margin:0;padding:0;box-sizing:border-box}body{width:1080px;height:1080px;overflow:hidden;font-family:'Segoe UI',Tahoma,sans-serif;background:linear-gradient(180deg,#0d2137 0%,#1a3a2a 100%);display:flex;flex-direction:column;justify-content:center;align-items:flex-start;padding:60px 80px}.circle{position:absolute;width:200px;height:200px;border:2px solid rgba(200,168,78,.1);border-radius:50%;top:-60px;right:-60px}h2{font-size:40px;color:#c8a84e;margin-bottom:32px;text-align:center;width:100%}.item{display:flex;align-items:flex-start;margin-bottom:24px}.dot{width:16px;height:16px;background:#c8a84e;border-radius:50%;margin-top:8px;margin-right:20px;flex-shrink:0}.content{flex:1}.year{font-size:22px;color:#c8a84e;font-weight:700}.text{font-size:22px;color:#b0c4b0;line-height:1.5;margin-top:4px}.text strong{color:#c8a84e}</style></head><body><div class="circle"></div><h2>📅 Jejak Islam di China</h2><div class="item"><div class="dot"></div><div class="content"><div class="year">651 M — Dinasti Tang</div><div class="text">Duta resmi Khulafaur Rasyidin tiba di hadapan Kaisar. Islam datang dengan <strong>salam, bukan pedang</strong>.</div></div></div><div class="item"><div class="dot"></div><div class="content"><div class="year">960 M — Dinasti Song</div><div class="text">Pedagang Muslim menikah dengan lokal → lahir etnis <strong>Hui</strong>. Quanzhou jadi pelabuhan tersibuk dunia.</div></div></div><div class="item"><div class="dot"></div><div class="content"><div class="year">1271 M — Dinasti Yuan (Mongol)</div><div class="text">Kubilai Khan angkat Muslim jadi <strong>menteri, gubernur, astronom</strong>. Era keemasan!</div></div></div><div class="item"><div class="dot"></div><div class="content"><div class="year">1405 M — Dinasti Ming</div><div class="text"><strong>Laksamana Zheng He</strong> — Muslim Hui — komandoi armada terbesar dunia. 87 tahun sebelum Columbus!</div></div></div></body></html>
EOF4

# Slide 5: Tokoh
cat > "$DIR/s5.html" << 'EOF5'
<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{margin:0;padding:0;box-sizing:border-box}body{width:1080px;height:1080px;overflow:hidden;font-family:'Segoe UI',Tahoma,sans-serif;background:linear-gradient(135deg,#1a3a2a 0%,#0d2137 100%);display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:60px}h2{font-size:40px;color:#c8a84e;margin-bottom:36px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;max-width:900px}.card{background:rgba(127,191,127,.08);border:1px solid rgba(127,191,127,.3);border-radius:16px;padding:28px;text-align:left}.name{font-size:26px;color:#7fbf7f;font-weight:700;margin-bottom:8px}.role{font-size:20px;color:#c8a84e;margin-bottom:8px}.desc{font-size:18px;color:#a0c0a0;line-height:1.5}</style></head><body><h2>⭐ Tokoh Muslim di Kekaisaran China</h2><div class="grid"><div class="card"><div class="name">Sa'ad bin Abi Waqqas</div><div class="role">Sahabat Nabi ﷺ</div><div class="desc">Duta pertama Islam ke China. Konon bangun Masjid Huaisheng di Guangzhou (627 M).</div></div><div class="card"><div class="name">Sayyid Ajall</div><div class="role">Gubernur Yunnan</div><div class="desc">Muslim dari Bukhara. Sebarkan Islam ke pedalaman China selatan. Bangun masjid & sekolah.</div></div><div class="card"><div class="name">Ahmad Fanakati</div><div class="role">Menteri Keuangan</div><div class="desc">Muslim yang mengelola keuangan kekaisaran terbesar di dunia di bawah Kubilai Khan.</div></div><div class="card"><div class="name">Laksamana Zheng He</div><div class="role">Komandan Armada</div><div class="desc">Muslim Hui. 7 ekspedisi laut, 27.800 pelaut. Sampai Afrika — 87 thn sebelum Columbus!</div></div></div></body></html>
EOF5

# Slide 6: Pelajaran
cat > "$DIR/s6.html" << 'EOF6'
<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{margin:0;padding:0;box-sizing:border-box}body{width:1080px;height:1080px;overflow:hidden;font-family:'Segoe UI',Tahoma,sans-serif;background:linear-gradient(135deg,#0d2137 0%,#1a3a2a 100%);display:flex;flex-direction:column;justify-content:center;align-items:center;padding:60px 80px}.circle{position:absolute;width:150px;height:150px;border:2px solid rgba(200,168,78,.1);border-radius:50%;bottom:-40px;left:-40px}h2{font-size:40px;color:#c8a84e;margin-bottom:36px}.lesson{display:flex;align-items:flex-start;margin-bottom:28px;max-width:850px;text-align:left}.num{width:56px;height:56px;background:#c8a84e;color:#0a0a1a;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:28px;font-weight:800;margin-right:20px;flex-shrink:0}.text{font-size:24px;color:#b0c4b0;line-height:1.5}.text strong{color:#c8a84e}</style></head><body><div class="circle"></div><h2>💡 Pelajaran untuk Kita</h2><div class="lesson"><div class="num">1</div><div class="text">Islam datang ke China dengan <strong>damai</strong> — lewat perdagangan & diplomasi. Bukan penaklukan. Akarnya justru paling dalam.</div></div><div class="lesson"><div class="num">2</div><div class="text">Muslim Hui membuktikan: <strong>100% Tionghoa + 100% Muslim</strong> itu mungkin. Tidak harus memilih.</div></div><div class="lesson"><div class="num">3</div><div class="text">Dinasti naik dan jatuh. Tapi Muslim <strong>tetap ada</strong>. 1.400 tahun — dan masih sholat Jumat.</div></div><div class="lesson"><div class="num">4</div><div class="text">Muslim bukan penonton — mereka <strong>aktor utama</strong> dalam sejarah China. Dari menteri sampai laksamana.</div></div></body></html>
EOF6

# Slide 7: Penutup
cat > "$DIR/s7.html" << 'EOF7'
<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{margin:0;padding:0;box-sizing:border-box}body{width:1080px;height:1080px;overflow:hidden;font-family:'Segoe UI',Tahoma,sans-serif;background:linear-gradient(135deg,#1a3a2a 0%,#0d2137 100%);display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:80px}.circle{position:absolute;width:200px;height:200px;border:2px solid rgba(200,168,78,.1);border-radius:50%}.c1{top:-60px;right:-60px}.c2{bottom:-40px;left:-40px;width:150px;height:150px}.quote{font-size:32px;color:#d4c080;font-style:italic;line-height:1.6;max-width:800px;margin-bottom:30px}.source{font-size:22px;color:#7fbf7f;margin-bottom:40px}.divider{width:80px;height:3px;background:#c8a84e;margin:0 auto 36px}.cta{background:rgba(200,168,78,.15);border:2px solid #c8a84e;border-radius:16px;padding:24px 40px;max-width:700px}.cta-text{font-size:24px;color:#c8a84e;line-height:1.5}.brand{position:absolute;bottom:40px;font-size:20px;color:rgba(200,168,78,.5)}</style></head><body><div class="circle c1"></div><div class="circle c2"></div><div class="quote">"Kami bukan pendatang. Kami adalah China."</div><div class="source">— Ma Zhengde, 78 tahun, Muslim Hui Shanghai</div><div class="divider"></div><div class="cta"><div class="cta-text">🕌 39.135 masjid. 30 juta Muslim. 1.400 tahun sejarah.<br><br>Islam tidak menaklukkan China.<br>Islam <strong>datang</strong> ke China — dan China membuka pintunya.</div></div><div class="brand">@bang_andriy ✨</div></body></html>
EOF7

echo "✅ All 7 slides created!"
